### ISSUE TITLE
Consistency troubles with nullable fields and ppx

### ISSUE THREAD

**Issue by TomiS** [DZakh/rescript-schema#66]
Hey. Trying to use the new ppx (fantastic job btw)

I have a bit "dirty" payload that has fields that can be either `undefined` or `null` or have some sort of value. The correct exact type is this:
```
    type item = {
      subscription: option<Null.t<subscription>>,
    }
```

I find it a bit confusing that `S.null` converts to `option` because now I need to type the payload differently based on whether I'm using ppx or not.

With ppx this works:
```
    @schema
    type item = {
      subscription: @schema(S.option(S.null(subscriptionSchema))) option<Null.t<subscription>>,
    }
```
But this doesn't (because ofc null !== undefined)
```
    @schema
    type item = {
      subscription: option<option<subscription>>,
    }
```

But then again, when using the lib without ppx this seems to be the way, right?
```
    type item = {
      subscription: option<option<subscription>>,
    }
    let itemSchema = S.object(s => {
      subscription: s.field("subscription", S.option(S.null(subscriptionSchema))),
    })

```
So maybe you can see what I mean when I say it's a bit confusing. Or maybe I'm doing something wrong?

Also it'd be nice if the lib/ppx could handle `Null.t` from rescript-core natively, maybe?

I'm using latest ReScript 11 rc.6 here with `rescript-core: 0.6.0` (not Belt)

**Comment by DZakh** [comment]
Thanks for reporting. It's an issue indeed. I'll fix it in the `6.3` release (eta 2-14 days)

**Comment by DZakh** [comment]
A correct work around should be:
```rescript
@schema
type item = {
  subscription: @schema(S.option(S.null(subscriptionSchema))) option<option<subscription>>,
}
```

**Comment by DZakh** [comment]
> Also, it might be a nice idea to add some sort of convenience solution for flattening null and option into one option. Decco did this for nullable optional fields "somehow". But unlike in decco, this could definitely be an opt-in.

Do you have an example how Decco handled nullable fields like this?

**Comment by TomiS** [comment]
I had to go back and check what really happens, but I got these results

```
let variableNull = %raw(`
{
  "variable": null,
  "other": 12
}
`)
let variableMissing = %raw(`
{
  "other": 12
}
`)
let variablePopulated = %raw(`
{
  "variable": "hello",
  "other": 12
}
`)
let variableUndefined = %raw(`
{
  "variable": undefined,
  "other": 12
}
`)

@decco
type obj = {variable: option<string>}

let decode = () => {
  Js.log(variableNull->obj_decode) // -> Ok undefined, i.e. None
  Js.log(variableMissing->obj_decode) // -> Ok undefined, i.e. None
  Js.log(variablePopulated->obj_decode) // -> Ok 'hello', i.e. Some(string)
  Js.log(variableUndefined->obj_decode) // -> Decoding fails, error 'not a string'
}
```
So both `null` and missing field decode to option `None`. In real life this is quite practical, because difference between null and option is rarely meaningful, and there is no need to flatMap nested options.

**Comment by DZakh** [comment]
Yes, I think the `S.optionOrNull` is what I'll do. And for ppx there'll be:
```rescript
@schema
type item = {
  subscription: @s.nullable option<subscription>,
}
```
What do you think?

**Comment by DZakh** [comment]
OK, I've decided. It'll be:
```
@schema
type item = {
  subscription: @s.nullable option<subscription>,
}
```
And `S.nullable` under the hood. I'll maybe even release it tomorrow.

**Comment by DZakh** [comment]
Done https://github.com/DZakh/rescript-schema/releases/tag/v6.3.0. Let me know how it works. I'm closing the issue for now.

**Comment by TomiS** [comment]
Very nice, thank you. And sorry I wan't able to provide feedback earlier.

It seems to work nicely and I can get rid of one extra option. The exact type I need to use now seems to be a bit more verbose than what you wrote above though. (But it's fine for me)
```
    @schema
    type item = {
      subscription: @schema(S.nullable(subscriptionSchema)) option<subscription>
    }
```

**Comment by DZakh** [comment]
Hm, weird, the
```
@schema
type item = {
  subscription: @s.nullable option<subscription>,
}
```
Should work the same as 
```
@schema
type item = {
  subscription: @schema(S.nullable(subscriptionSchema)) option<subscription>
}
```

**Comment by TomiS** [comment]
Ah, you're correct. It does work. I misread it and made a typo when I tried last time.

**Comment by DZakh** [comment]
> Ah, you're correct. It does work. I misread it and made a typo when I tried last time.

What kind of typo? Maybe I can add some validation for attiributes 🤔

**Comment by TomiS** [comment]
Nah, it was just this. It's a syntax error anyway, so dunno if it needs anything.
```
      subscriptions: S.nullable option<subscription>,
```

**Comment by DZakh** [comment]
Ah, I see 😁
