### ISSUE TITLE
[PPX] Cannot use @as inside inline records

### ISSUE THREAD

**Issue by tsnobip** [DZakh/rescript-schema#69]
Hey, thanks a lot for the lib and for the PPX!

I bumped into this issue, let's say you define a variant with inline records like this:
```res
@schema @tag("type")
type t =
  | @as("foo") Foo({@as("Foo") foo: string})
  | @as("bar") Bar({@as("Bar") bar: string})
```
You would get the following error:
```
The field Foo is not part of the record argument for the t.Foo constructor
Hint: Did you mean foo?
```

I don't know if it's a known issue or if it could be fixed.

**Comment by DZakh** [comment]
Thanks for reporting, it should work. I'll investigate and try to do a fix.

**Comment by DZakh** [comment]
Fixed in https://github.com/DZakh/rescript-schema/releases/tag/v6.4.0

**Comment by tsnobip** [comment]
> Fixed in https://github.com/DZakh/rescript-schema/releases/tag/v6.4.0

Wow thanks a lot!
