### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by mcharnet** [DZakh/rescript-schema#70]
Hello @DZakh !

First, thanks for your work, it looks amazing !

I want to switch from decco to rescript-schema in my project, but I encounter an error while compiling. I'm using Rescript v11 (without uncurried mode) and Next.js. Here is the error : 

```
./node_modules/rescript-schema/src/S.res.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (13:0)
| };
| // Generated by ReScript, PLEASE EDIT WITH CARE
> import * as S_Core$RescriptSchema from "./S_Core.res.js";
| var Literal = S_Core$RescriptSchema.Literal;
| var Path_toArray = S_Core$RescriptSchema.Path.toArray;
```

It may be a configuration issue, but I don't know where to investigate. I'm using `es6-global` as module in my package-specs. 
Do you have an idea which could help me ?

Thanks !

**Comment by DZakh** [comment]
Can you try using `es6` instead of `es6-global`. If it doesn't help, try changing suffix to `.res.mjs` instead of `.res.js`
