### ISSUE TITLE
[Suggestion] Support @tag from ppx 

### ISSUE THREAD

**Issue by DCKT** [DZakh/rescript-schema#71]
Hello,

Now with ReScript v11, we are able to create a discriminant tag with [`@tag` directive](https://rescript-lang.org/blog/improving-interop#tagged-variants).  
I think it could be awesome to have it support through ppx to reduce the boilerplate.

Based on the [union example](https://github.com/DZakh/rescript-schema/blob/main/docs/rescript-usage.md#union) : 
```rescript
// TypeScript type for reference:
// type Shape =
// | { kind: "circle"; radius: number }
// | { kind: "square"; x: number }
// | { kind: "triangle"; x: number; y: number };
type shape = Circle({radius: float}) | Square({x: float}) | Triangle({x: float, y: float})

let shapeSchema = S.union([
  S.object(s => {
    s.tag("kind", "circle")
    Circle({
      radius: s.field("radius", S.float),
    })
  }),
  S.object(s => {
    s.tag("kind", "square")
    Square({
      x: s.field("x", S.float),
    })
  }),
  S.object(s => {
    s.tag("kind", "triangle")
    Triangle({
      x: s.field("x", S.float),
      y: s.field("y", S.float),
    })
  }),
])
```

Could become something like this : 
```rescript
@schema @tag("kind")
type shape = 
  | @as("circle") Circle({radius: float}) 
  | @as("square") Square({x: float}) 
  | @as("triangle") Triangle({x: float, y: float})
```

My skills for ppx development are pretty low so I don't really know if it's something difficult or not, sorry in advance 😅 . If it's an easy addition, I would be glad to help :)

Thanks for the lib and your awesome work !

**Comment by DZakh** [comment]
If I understood you correctly, it's already supported 😁 You can find the documentation [here].(https://github.com/DZakh/rescript-schema/blob/main/packages/rescript-schema-ppx/README.md)

**Comment by DCKT** [comment]
Oh indeed ! I tried before posting the issue and my tag value was wrong 🙄 . 
Thanks for your quick answer

**Comment by DZakh** [comment]
Maybe it was because of the issue https://github.com/DZakh/rescript-schema/issues/69
