### ISSUE TITLE
Incorrect parsing with S.object + S.nullable + S.refine

### ISSUE THREAD

**Issue by cknitt** [DZakh/rescript-schema#79]
The following seems to be a regression in rescript-schema 7 + 8. It works fine in rescript-schema 6.

```rescript
let jsonString = `{"myField": "test"}`

let schema = S.object(s => s.field("myField", S.option(S.string)))->S.refine(_ => _ => ())
// ✅ { TAG: 'Ok', _0: 'test' }
Console.log(S.parseJsonStringWith(jsonString, schema))

let schema = S.object(s => s.field("myField", S.nullable(S.string)))->S.refine(_ => _ => ())
// 😱 { TAG: 'Ok', _0: undefined }
Console.log(S.parseJsonStringWith(jsonString, schema))
```

**Comment by DZakh** [comment]
😳

**Comment by DZakh** [comment]
I've found the issue. I'll take a look at how I can change the core of the library to prevent this kind of error in the future. Probably release a fix this weekends. Have big workload next two days.

**Comment by DZakh** [comment]
Thank you for finding loopholes in my tests. There are almost a 1k of them, but that's still not enough 😅

**Comment by DZakh** [comment]
https://github.com/DZakh/rescript-schema/releases/tag/v8.0.1 with a fix is published. Thank you for reporting
