### ISSUE TITLE
(docs/typing) refinement's s.fail returns void despite being thrown

### ISSUE THREAD

**Issue by dearlordylord** [DZakh/rescript-schema#82]
This works runtime and compile time, but just has a bit weird typing: I haven't encountered "voids" being thrown before

ref: https://github.com/DZakh/rescript-schema/blob/main/docs/js-usage.md#refinements

<img width="873" alt="Screenshot 2024-07-29 at 12 08 11 AM" src="https://github.com/user-attachments/assets/e75fec91-f5cf-4829-bf6b-12694a12a2b1">
<img width="421" alt="Screenshot 2024-07-29 at 12 05 22 AM" src="https://github.com/user-attachments/assets/93b68f46-4a80-4582-acf4-920906e4df18">

**Comment by DZakh** [comment]
Actually, `s.fail` throws itself, so it should probably return `never` instead. I'll fix it 🫡

**Comment by DZakh** [comment]
Done in [8.0.3](https://github.com/DZakh/rescript-schema/releases/tag/v8.0.3)
