### ISSUE TITLE
(docs) consider explicitly mentioning email validation incompleteness

### ISSUE THREAD

**Issue by dearlordylord** [DZakh/rescript-schema#83]
Several parser libraries include disclaimers about email validation:

https://valibot.dev/api/email/

https://github.com/ianstormtaylor/superstruct?tab=readme-ov-file#why

https://github.com/effect-ts/effect/tree/main/packages/schema#email

https://github.com/jquense/yup?tab=readme-ov-file#stringemailmessage-string--function-schema 

I think it's good to have this reminder; I've seen many beginner developers using email regex blindly without realizing pros and cons.

**Comment by DZakh** [comment]
Copied the regex from Zod 😁

**Comment by DZakh** [comment]
Done, thank you for the suggestion https://github.com/DZakh/rescript-schema/blob/main/docs/js-usage.md#strings
