### ISSUE TITLE
Q: transforming string to int

### ISSUE THREAD

**Issue by nojaf** [DZakh/rescript-schema#85]
Hello,

This is probably more of question than an actual issue.
I want to define a field that will be a string value but should actually be convertible to an integer.

Something like:

```res
type yow = {
  x: int,
  y: string,
}

exception NotAnInt

let transformer: S.transformDefinition<string, int> = {
  asyncParser: s => {
    switch s->Int.fromString {
    | None => () => Promise.reject(NotAnInt)
    | Some(i) => () => Promise.resolve(i)
    }
  },
}

let yowSchema = S.object(s => {
  {
    x: s.field("x", S.string->S.transform(_ => transformer)),
    y: s.field("y", S.string),
  }
})

let formData = %raw(`{ "x": "1", "y": "yow" }`)

S.parseAnyWith(yowSchema, formData)->Console.log
```

This code compiles, but I'm wondering if this is correct usage of the library?
Or am I abusing promises in this case?

(Side note, I can't run the compiled version of this, `bun src/Yow.re.js`)

```
941 | 
942 | function parseAnyWith(any, schema) {
943 |   try {
944 |     return {
945 |             TAG: "Ok",
946 |             _0: schema.parseOrThrow(any)
                             ^
TypeError: schema.parseOrThrow is not a function. (In 'schema.parseOrThrow(any)', 'schema.parseOrThrow' is undefined)
      at parseAnyWith (/home/nojaf/projects/my-pkmn-rescript-app/node_modules/rescript-schema/src/S_Core.re.js:946:24)
      at /home/nojaf/projects/my-pkmn-rescript-app/src/Yow.re.js:39:30

Bun v1.1.24 (Linux x64)
```

**Comment by DZakh** [comment]
I think the problem is that you use sync `parseAnyWith` to parse a schema with async transform. You should use `parseAsyncWith` or something like this.

I don't know why you get such a weird error though, since it should be handled nicely. I'll double check, since I remember covering it with a test.

But in your case I think I shouldn't used async transform and instead do:

```rescript
type yow = {
  x: int,
  y: string,
}

let stringSchemaToInt = schema => schema->S.transform(s => {
  parser: string => {
    switch string->Int.fromString {
    | None => s.fail("Invalid Int value")
    | Some(int) => int
    }
  }
})

let yowSchema = S.object(s => {
  {
    x: s.field("x", S.string->stringSchemaToInt,
    y: s.field("y", S.string),
  }
})

let formData = %raw(`{ "x": "1", "y": "yow" }`)

formData->S.parseAnyWith(yowSchema)->Console.log
```

**Comment by DZakh** [comment]
Ah, when I was fixing your example, I noticed why you get such a weird error 😁

In the line `S.parseAnyWith(yowSchema, formData)->Console.log` the `yowSchema` should come as a second argument, since `S.parseAnyWith` is a data-first function for more convenient piping.

**Comment by DZakh** [comment]
I hope my example helped

**Comment by nojaf** [comment]
Yes, thank you!
