### ISSUE TITLE
Documentation for Discriminated Unions in TypeScript

### ISSUE THREAD

**Issue by justin0mcateer** [DZakh/rescript-schema#86]
Thanks for your hard work. I have been looking forward to using this library for a while. Starting my first project with it, things are going pretty well, very easy to use and quite powerful.

One issue I have run into is it's not clear to me what is the correct way to implement discriminated unions. I found some older issues which referenced 'discriminator' and 'field' with 'ignore'. I wasn't really able to put any of this into practice. Some specific documentation on discriminated types in the TypeScript documentation would be super helpful.

**Comment by DZakh** [comment]
It's a good point. The closest you can use is the rescript documentation https://github.com/DZakh/rescript-schema/blob/main/docs/rescript-usage.md#union
TS code should look pretty much the same. I don't remember if I added s.tag support, but you can use s.field("", S.literal()) instead

**Comment by DZakh** [comment]
I've got an idea of how to make it even more ergonomic and convenient for the JS/TS users. I'll add the feature in the next version together with the documentaion.

**Comment by justin0mcateer** [comment]
Awesome!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DZakh** [comment]
Here's the documentation update for the feature: https://github.com/DZakh/rescript-schema/commit/4b0d45625b3e81515586083cf9600b0b164b427b

I'll release it as `8.1.0` after ci finishes running.

**Comment by DZakh** [comment]
Published

**Comment by justin0mcateer** [comment]
I did get it working, based on your previous pointers. 

The new approach you documented looks very concise. Love it!
